CREATE schema IF NOT EXISTS users;

CREATE TABLE users.user(
    id BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    cpf VARCHAR(100) NOT NULL,
    adress VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telephone VARCHAR(100) NOT NULL,
    date_registry TIMESTAMP
);