CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE users.USER (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    cpf VARCHAR(100) NOT NULL,
    adress VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telephone VARCHAR(100) NOT NULL,
    registry_date TIMESTAMP NOT NULL
);